/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Random;

public class App {
    Quotes quote;

    public App() throws FileNotFoundException {
        getData();
    }

    public void getData() throws FileNotFoundException {
        Gson gson = new Gson();
        Quotes[] dataFromJson = gson.fromJson(new FileReader("src/main/resources/recentquotes.json"), Quotes[].class);

        int randomIndex = randInt(0, dataFromJson.length);
        while(dataFromJson[randomIndex].author == null || dataFromJson[randomIndex].text == null){
            randomIndex = randInt(0, dataFromJson.length);
        }
        this.quote = dataFromJson[randomIndex];
    }

    public int randInt(int min, int max){
        Random rand = new Random();
        int randomNum = rand.nextInt((max - min) + 1) + min;
        return randomNum;
    }

    @Override
    public String toString(){
        return String.format("The author: %s is quoted:%s",this.quote.author,this.quote.text);
    }

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws FileNotFoundException {

        System.out.println("*******************************");
        App quoteApp = new App();
        System.out.println(quoteApp);
    }
}
