/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Random;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static int randInt(int min, int max){
        Random rand = new Random();
        int randomNum = rand.nextInt((max - min) + 1) + min;
        return randomNum;
    }

    public static void main(String[] args) throws FileNotFoundException {

        System.out.println(new App().getGreeting());



        Gson gson = new Gson();
        Quotes[] dataFromJson = gson.fromJson(new FileReader("src/main/resources/recentquotes.json"), Quotes[].class);
        System.out.println(gson.toJson(dataFromJson));
        System.out.println(dataFromJson.length);

        int randomIndex = randInt(0, dataFromJson.length);
        while(dataFromJson[randomIndex].author == null || dataFromJson[randomIndex].text == null){
            randomIndex = randInt(0, dataFromJson.length);
        }

        System.out.println(dataFromJson[randomIndex].author);
        System.out.println(dataFromJson[randomIndex].text);


    }
}
class Quotes{
    String[] tags;
    String author;
    String likes;
    String text;
}